# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160811233531 on 2016-09-26 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('account_time', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
