# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160811233531 on 2016-09-26 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsManage',
            fields=[
                ('id', models.AutoField(auto_created=True, serialize=False, verbose_name='ID')),# , primary_key=True
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('body_des', models.TextField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
                ('blog_type', models.CharField(max_length=50)),
                ('blog_imgurl', models.CharField(max_length=50, null=True)),
            ],
            options={
                'indexes': [],
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('work', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=20)),
            ],
            options={
                'indexes': [],
            },
        ),
    ]
