# -*- coding: utf-8 -*-
# Generated by Django 1.11.dev20160811233531 on 2016-10-08 06:36
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsmanage',
            name='body',
            field=DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5185\u5bb9'),
        ),
    ]
